# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/fih/fb0/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/huawei/u8850/proprietary/lib/libaudioalsa.so:/obj/lib/libaudioalsa.so 
       
# All the blobs necessary for fb0
PRODUCT_COPY_FILES += \
    vendor/huawei/u8850/proprietary/bin/qmuxd:/system/bin/qmuxd \
    vendor/huawei/u8850/proprietary/bin/hci_qcomm_init:/system/bin/hci_qcomm_init \
    vendor/huawei/u8850/proprietary/bin/geomagneticd:/system/bin/geomagneticd \
    vendor/huawei/u8850/proprietary/bin/orientationd:/system/bin/orientationd \
    vendor/huawei/u8850/proprietary/bin/proximityd:/system/bin/proximityd \
    vendor/huawei/u8850/proprietary/bin/lightd:/system/bin/lightd \
    vendor/huawei/u8850/proprietary/bin/nt_password_hash:/system/bin/nt_password_hash \
    vendor/huawei/u8850/proprietary/bin/hlr_auc_gw:/system/bin/hlr_auc_gw \
    vendor/huawei/u8850/proprietary/bin/hciattach:/system/bin/hciattach \
    vendor/huawei/u8850/proprietary/bin/hostapd:/system/bin/hostapd \
    vendor/huawei/u8850/proprietary/bin/hostapd_cli:/system/bin/hostapd_cli \
    vendor/huawei/u8850/proprietary/bin/netmgrd:/system/bin/netmgrd \
    vendor/huawei/u8850/proprietary/bin/rmt_storage:/system/bin/rmt_storage \
    vendor/huawei/u8850/proprietary/bin/port-bridge:/system/bin/port-bridge \
    vendor/huawei/u8850/proprietary/bin/btwlancoex:/system/bin/btwlancoex \
    vendor/huawei/u8850/proprietary/lib/libgemini.so:/system/lib/libgemini.so \
    vendor/huawei/u8850/proprietary/lib/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/u8850/proprietary/lib/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/huawei/u8850/proprietary/lib/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/u8850/proprietary/lib/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/u8850/proprietary/lib/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/u8850/proprietary/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/huawei/u8850/proprietary/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/huawei/u8850/proprietary/lib/libC2D2.so:/system/lib/libC2D2.so \
    vendor/huawei/u8850/proprietary/lib/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/huawei/u8850/proprietary/lib/sensors.fb0.so:/system/lib/hw/sensors.fb0.so \
    vendor/huawei/u8850/proprietary/lib/libcommondefs.so:/system/lib/libcommondefs.so \
    vendor/huawei/u8850/proprietary/lib/libgps.so:/system/lib/libgps.so \
    vendor/huawei/u8850/proprietary/lib/libloc_api-rpc-qc.so:/system/lib/libloc_api-rpc-qc.so \
    vendor/huawei/u8850/proprietary/lib/libloc_ext.so:/system/lib/libloc_ext.so \
    vendor/huawei/u8850/proprietary/lib/libloc-rpc.so:/system/lib/libloc-rpc.so \
    vendor/huawei/u8850/proprietary/lib/gps.fb0.so:/system/lib/hw/gps.fb0.so \
    vendor/huawei/u8850/proprietary/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/huawei/u8850/proprietary/bin/rild:/system/bin/rild \
    vendor/huawei/u8850/proprietary/lib/libril.so:/system/lib/libril.so \
    vendor/huawei/u8850/proprietary/lib/libril-qc-1.so:/system/lib/libril-qc-1.so \
    vendor/huawei/u8850/proprietary/lib/libreference-ril.so:/system/lib/libreference-ril.so \
    vendor/huawei/u8850/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8850/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
    vendor/huawei/u8850/proprietary/lib/liboncrpc.so:/system/lib/liboncrpc.so \
    vendor/huawei/u8850/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
    vendor/huawei/u8850/proprietary/lib/libdsm.so:/system/lib/libdsm.so \
    vendor/huawei/u8850/proprietary/lib/libqueue.so:/system/lib/libqueue.so \
    vendor/huawei/u8850/proprietary/lib/libcm.so:/system/lib/libcm.so \
    vendor/huawei/u8850/proprietary/lib/libmmgsdilib.so:/system/lib/libmmgsdilib.so \
    vendor/huawei/u8850/proprietary/lib/libgsdi_exp.so:/system/lib/libgsdi_exp.so \
    vendor/huawei/u8850/proprietary/lib/libgstk_exp.so:/system/lib/libgstk_exp.so \
    vendor/huawei/u8850/proprietary/lib/libwms.so:/system/lib/libwms.so \
    vendor/huawei/u8850/proprietary/lib/libnv.so:/system/lib/libnv.so \
    vendor/huawei/u8850/proprietary/lib/libwmsts.so:/system/lib/libwmsts.so \
    vendor/huawei/u8850/proprietary/lib/libpbmlib.so:/system/lib/libpbmlib.so \
    vendor/huawei/u8850/proprietary/lib/libauth.so:/system/lib/libauth.so \
    vendor/huawei/u8850/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
    vendor/huawei/u8850/proprietary/lib/libidl.so:/system/lib/libidl.so \
    vendor/huawei/u8850/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
    vendor/huawei/u8850/proprietary/lib/liboem_rapi.so:/system/lib/liboem_rapi.so \
    vendor/huawei/u8850/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/huawei/u8850/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/huawei/u8850/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/huawei/u8850/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/huawei/u8850/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8850/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/u8850/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/u8850/proprietary/lib/camera.fb0.so:/system/lib/hw/camera.fb0.so

# Prebuilt libraries from CodeAurora
PRODUCT_COPY_FILES += \
    vendor/huawei/u8850/proprietary/lib/libv8.so:system/lib/libv8.so \
    vendor/huawei/u8850/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/huawei/u8850/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/huawei/u8850/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/huawei/u8850/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so

